import type {Enemy,Input} from '../sim/types';
import type {View} from '../render/renderer';
export class Controls {
 assist=.3;keys=new Set<string>();mouse={x:innerWidth*.65,y:innerHeight*.5,down:false};dodge=false;deadeye=false;usingPad=false;padAim=0;previousButtons:boolean[]=[];bindings={up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',dodge:'Space',deadeye:'KeyE'};toggle=false;toggleDown=false;
 constructor(){addEventListener('keydown',e=>{if(e.repeat)return;this.keys.add(e.code);if(e.code===this.bindings.dodge){this.dodge=true;e.preventDefault();}if(e.code===this.bindings.deadeye)this.deadeye=true;});addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('pointermove',e=>{this.mouse.x=e.clientX;this.mouse.y=e.clientY;this.usingPad=false;});addEventListener('pointerdown',e=>{if((e.target as HTMLElement).closest('button,input,.slu-ui-panel'))return;if(e.button===0){this.mouse.down=true;this.toggleDown=!this.toggleDown;}if(e.button===2)this.deadeye=true;});addEventListener('pointerup',e=>{if(e.button===0)this.mouse.down=false;});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('blur',()=>this.clear());}
 clear(){this.keys.clear();this.mouse.down=false;this.toggleDown=false;this.dodge=false;this.deadeye=false;}
 sample(view:View,player:{x:number;y:number},targets:readonly Enemy[]=[]):Input {
  let mx=Number(this.keys.has(this.bindings.right))-Number(this.keys.has(this.bindings.left)),my=Number(this.keys.has(this.bindings.down))-Number(this.keys.has(this.bindings.up));let aim=view.screenToWorld(this.mouse.x,this.mouse.y);let draw=this.toggle?this.toggleDown:this.mouse.down;
  const pad=Array.from(navigator.getGamepads?.()??[]).find(Boolean);if(pad){const pressed=pad.buttons.map(b=>b.pressed),edge=(i:number)=>pressed[i]&&!this.previousButtons[i];const lx=pad.axes[0]||0,ly=pad.axes[1]||0,rx=pad.axes[2]||0,ry=pad.axes[3]||0;if(Math.hypot(lx,ly)>.15){mx=lx;my=ly;this.usingPad=true;}if(Math.hypot(rx,ry)>.2){this.padAim=Math.atan2(ry,rx);this.usingPad=true;}if(this.usingPad){let best:Enemy|undefined,bestAngle=.22;for(const e of targets)if(e.active&&!e.deadmark){const angle=Math.atan2(e.y-player.y,e.x-player.x),delta=Math.abs(Math.atan2(Math.sin(angle-this.padAim),Math.cos(angle-this.padAim)));if(delta<bestAngle&&Math.hypot(e.x-player.x,e.y-player.y)<800){best=e;bestAngle=delta;}}if(best&&this.assist>0){const angle=Math.atan2(best.y-player.y,best.x-player.x);this.padAim+=Math.atan2(Math.sin(angle-this.padAim),Math.cos(angle-this.padAim))*this.assist;}aim={x:player.x+Math.cos(this.padAim)*400,y:player.y+Math.sin(this.padAim)*400};this.mouse.x=view.width/2+(aim.x-view.camera.x)*view.zoom;this.mouse.y=view.height/2+(aim.y-view.camera.y)*view.zoom;}draw=draw||pressed[7];this.dodge=this.dodge||edge(0)||edge(6);this.deadeye=this.deadeye||edge(5);this.previousButtons=pressed;}
  view.aimScreen.x=this.mouse.x;view.aimScreen.y=this.mouse.y;const input={mx,my,ax:aim.x,ay:aim.y,draw,dodge:this.dodge,deadeye:this.deadeye};this.dodge=false;this.deadeye=false;return input;
 }
}
